import { useMemo, useState } from "react";
import { Search, Shuffle, X, ExternalLink, Wrench, ShieldCheck } from "lucide-react";

const img = (file: string) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}`;
const src = (file: string) => `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(file).replace(/%20/g, "_")}`;

type Item = { id:string; name:string; cat:"Cables"|"Tools"|"Test equipment"; image:string; purpose:string; exam:string; tip:string; source:string };
const ITEMS: Item[] = [
 {id:"hdmi",name:"HDMI",cat:"Cables",image:img("HDMI-Connector.jpg"),purpose:"Digital audio/video connection for computers, displays, TVs and projectors.",exam:"Wide, tapered Type A connector. Digital video and audio.",tip:"HDMI carries digital video AND audio on one connection.",source:src("HDMI-Connector.jpg")},
 {id:"dp",name:"DisplayPort",cat:"Cables",image:img("Displayport-cable.jpg"),purpose:"Digital display interface commonly used for computer monitors.",exam:"Rectangular plug with one clipped corner; standard plugs commonly latch.",tip:"Do not confuse DisplayPort with HDMI.",source:src("Displayport-cable.jpg")},
 {id:"dvi",name:"DVI",cat:"Cables",image:img("Dvi-cable.jpg"),purpose:"Older display interface. Variants can carry digital, analog, or both.",exam:"Large connector with a grid of pins and a flat blade.",tip:"DVI-D is digital; DVI-A analog; DVI-I can carry both.",source:src("Dvi-cable.jpg")},
 {id:"vga",name:"VGA",cat:"Cables",image:img("Vga-cable.jpg"),purpose:"Legacy analog video connection using a 15-pin DE-15 connector.",exam:"15 pins in three rows plus screw posts. Analog video.",tip:"VGA is analog; HDMI and DisplayPort are digital.",source:src("Vga-cable.jpg")},
 {id:"usbc",name:"USB-C",cat:"Cables",image:img("USB Type-C.jpg"),purpose:"Reversible USB connector used for data, charging and sometimes display output.",exam:"Small oval/reversible connector. Capabilities depend on the port and cable.",tip:"Connector shape alone does not reveal USB speed or feature set.",source:src("USB Type-C.jpg")},
 {id:"usb",name:"USB Type-A",cat:"Cables",image:img("USB-cable.jpg"),purpose:"Common rectangular USB connector used for PC peripherals and data transfer.",exam:"Recognize the familiar rectangular Type-A plug.",tip:"Connector shape and USB generation are separate concepts.",source:src("USB-cable.jpg")},
 {id:"rj45",name:"RJ45 / 8P8C Ethernet",cat:"Cables",image:img("RJ45 Ethernet Cable.jpg"),purpose:"Twisted-pair Ethernet connection for LAN networking with eight contacts.",exam:"Modular 8P8C plug with locking tab; larger than telephone-style RJ11.",tip:"Know T568A vs T568B and the 100 m copper Ethernet concept.",source:src("RJ45 Ethernet Cable.jpg")},
 {id:"sata",name:"SATA data cable",cat:"Cables",image:img("SATA Cable (4816965007).jpg"),purpose:"Serial ATA data connection for compatible storage devices.",exam:"Thin data cable; do not confuse it with the wider SATA power connector.",tip:"SATA data and SATA power are separate connections.",source:src("SATA Cable (4816965007).jpg")},
 {id:"crimper",name:"RJ45 crimper",cat:"Tools",image:img("Crimping tool TP2.jpg"),purpose:"Terminates modular RJ45/8P8C plugs onto twisted-pair cable.",exam:"Use it for modular plugs—not for seating wires in a keystone jack.",tip:"Crimper = modular plug. Punchdown = IDC/keystone/patch-panel termination.",source:src("Crimping tool TP2.jpg")},
 {id:"punchdown",name:"Punchdown tool",cat:"Tools",image:img("Punch-down-tool-Krone-and-110-0a.jpg"),purpose:"Seats conductors into IDC terminals such as 110 or Krone blocks.",exam:"Use it for keystone jacks and patch panels.",tip:"Punchdown is not the tool for crimping RJ45 plugs.",source:src("Punch-down-tool-Krone-and-110-0a.jpg")},
 {id:"tester",name:"Cable tester",cat:"Test equipment",image:img("Cabletester.jpg"),purpose:"Checks continuity and wiring faults such as opens, shorts and incorrect pinouts.",exam:"Use after terminating a network cable to verify wiring.",tip:"A cable tester verifies the cable, not the entire network path.",source:src("Cabletester.jpg")},
 {id:"meter",name:"Digital multimeter",cat:"Test equipment",image:img("All multimeters.jpg"),purpose:"Measures electrical quantities such as voltage, resistance and current.",exam:"Select the correct mode and lead ports. Never measure resistance on an energized circuit.",tip:"DMM = digital multimeter; learn what each dial position measures.",source:src("All multimeters.jpg")}
];
const CATS=["All","Cables","Tools","Test equipment"] as const;

export function ToolsLabView(){
 const [q,setQ]=useState(""); const [cat,setCat]=useState<(typeof CATS)[number]>("All"); const [open,setOpen]=useState<Item|null>(null); const [quiz,setQuiz]=useState<Item|null>(null); const [answer,setAnswer]=useState<string|null>(null);
 const shown=useMemo(()=>ITEMS.filter(x=>(cat==="All"||x.cat===cat)&&(!q||`${x.name} ${x.cat} ${x.purpose} ${x.exam}`.toLowerCase().includes(q.toLowerCase()))),[q,cat]);
 const start=()=>{const p=shown.length?shown:ITEMS;setQuiz(p[Math.floor(Math.random()*p.length)]);setAnswer(null)};
 const next=()=>{const p=(shown.length?shown:ITEMS).filter(x=>x.id!==quiz?.id);setQuiz(p[Math.floor(Math.random()*p.length)]??ITEMS[0]);setAnswer(null)};
 return <div className="pb-8">
  <header className="rounded-3xl border border-border bg-panel p-5 shadow-sm sm:p-7">
   <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-accent"><Wrench className="h-4 w-4"/>Technician Lab</div><h1 className="font-display text-3xl font-medium tracking-tight sm:text-4xl">Tools & Visual Reference</h1><p className="mt-2 max-w-2xl text-muted">Real equipment photos. Learn what it is, what it does, and the exact exam trap before you get tested on it.</p></div><button onClick={start} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-accent px-5 font-semibold text-white"><Shuffle className="h-4 w-4"/>Visual ID drill</button></div>
   <div className="mt-6 flex flex-col gap-3"><label className="flex min-h-12 items-center gap-3 rounded-2xl border border-border bg-bg px-4"><Search className="h-5 w-5 text-faint"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search HDMI, crimper, tester…" className="w-full bg-transparent text-sm outline-none placeholder:text-faint"/></label><div className="flex gap-2 overflow-x-auto pb-1">{CATS.map(c=><button key={c} onClick={()=>setCat(c)} className={`min-h-11 shrink-0 rounded-2xl border px-4 text-sm font-medium ${cat===c?"border-accent bg-accent/10 text-accent":"border-border bg-bg text-muted"}`}>{c}</button>)}</div></div>
  </header>
  <div className="mt-5 flex items-center justify-between px-1"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-faint">Visual library</p><p className="mt-1 text-sm text-muted">{shown.length} photo-based study items · tap to inspect</p></div><div className="hidden items-center gap-2 text-xs text-faint sm:flex"><ShieldCheck className="h-4 w-4"/>Source-linked</div></div>
  <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{shown.map(x=><button key={x.id} onClick={()=>setOpen(x)} className="group overflow-hidden rounded-3xl border border-border bg-panel text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="relative aspect-[4/3] overflow-hidden bg-bg"><img src={x.image} alt={x.name} loading="lazy" className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]"/><span className="absolute left-2 top-2 rounded-full bg-black/70 px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-white">PHOTO</span></div><div className="p-3 sm:p-4"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-faint">{x.cat}</p><h2 className="mt-1 text-sm font-semibold sm:text-base">{x.name}</h2><p className="mt-2 line-clamp-2 text-xs leading-relaxed text-muted">{x.purpose}</p></div></button>)}</div>
  {open&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center sm:p-5" onClick={()=>setOpen(null)}><div className="max-h-[94dvh] w-full overflow-y-auto rounded-t-3xl bg-panel p-5 sm:max-w-2xl sm:rounded-3xl sm:p-7" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-accent">{open.cat}</p><h2 className="mt-1 font-display text-2xl">{open.name}</h2></div><button onClick={()=>setOpen(null)} className="rounded-full p-2 text-muted hover:bg-bg"><X/></button></div><div className="mt-5 overflow-hidden rounded-2xl bg-bg"><img src={open.image} alt={open.name} className="max-h-[48dvh] w-full object-contain"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><section className="rounded-2xl border border-border bg-bg p-4"><p className="text-xs font-semibold uppercase tracking-wider text-faint">What it does</p><p className="mt-2 text-sm leading-relaxed">{open.purpose}</p></section><section className="rounded-2xl border border-border bg-bg p-4"><p className="text-xs font-semibold uppercase tracking-wider text-faint">Exam recognition</p><p className="mt-2 text-sm leading-relaxed">{open.exam}</p></section></div><section className="mt-3 rounded-2xl border border-accent/20 bg-accent/5 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-accent">Technician tip</p><p className="mt-2 text-sm leading-relaxed">{open.tip}</p></section><a href={open.source} target="_blank" rel="noreferrer" className="mt-4 inline-flex text-xs text-muted underline underline-offset-4"><ExternalLink className="mr-2 h-3.5 w-3.5"/>Image source / license</a></div></div>}
  {quiz&&<div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/70 sm:items-center sm:p-5" onClick={()=>setQuiz(null)}><div className="max-h-[94dvh] w-full overflow-y-auto rounded-t-3xl bg-panel p-5 sm:max-w-xl sm:rounded-3xl sm:p-7" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-accent">Visual ID drill</p><p className="mt-1 text-sm text-muted">Identify the item from the photo.</p></div><button onClick={()=>setQuiz(null)} className="rounded-full p-2 text-muted hover:bg-bg"><X/></button></div><div className="mt-5 overflow-hidden rounded-2xl bg-bg"><img src={quiz.image} alt="Identify this item" className="max-h-[50dvh] w-full object-contain"/></div>{!answer?<div className="mt-4 grid grid-cols-2 gap-2">{[quiz.name,...ITEMS.filter(x=>x.id!==quiz.id).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.name)].sort(()=>Math.random()-.5).map(a=><button key={a} onClick={()=>setAnswer(a)} className="min-h-14 rounded-2xl border border-border bg-bg px-3 text-sm font-medium">{a}</button>)}</div>:<div className={`mt-4 rounded-2xl border p-4 ${answer===quiz.name?"border-green-500/30 bg-green-500/10":"border-red-500/30 bg-red-500/10"}`}><p className="font-semibold">{answer===quiz.name?"Correct.":`Not quite — it is ${quiz.name}.`}</p><p className="mt-2 text-sm leading-relaxed text-muted">{quiz.exam}</p><button onClick={next} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl bg-accent px-4 text-sm font-semibold text-white"><Shuffle className="h-4 w-4"/>Next item</button></div>}</div></div>}
 </div>;
}
